server:
    idletimeout: 4s
    readtimeout: 4s
    writetimeout: 4s
    port: "8080"

database:
    dsn: "root@tcp(localhost:3306/localdb"
    dialect: "mysql"
    connectUri: "/localdb?charset=utf8&parseTime=True"
    username: "root"
    password: ""