kind: ConfigMap
apiVersion: v1
metadata:
  name: gorestapiclient-config
data:
  config.yml: |-
    server:
     idletimeout: 5s
     readtimeout: 5s
     writetimeout: 5s
     addr: ":9804"

    database:
      dsn: "root:pwd@tcp(dbservice:3306)/localdb?charset=utf8&parseTime=Tru"